### ISSUE TITLE
Service Not Reachable

### ISSUE THREAD

**Issue by onlinejudge95** [garutilorenzo/docker-swarm-ingress#14]
I have the following setup of a 4-node cluster with a single master and 3 worker nodes. I run the following services that I am interested in proxy behind this ingress.

- Visualizer (Bare minimum tool for visualizing the swarm cluster), this runs on the same manager node and I can reach it via the proxy
- React UI, this service is up and running and I have made the required changes but while going through the URL I get a 504 timeout.

Here are the corresponding stack files for ingress and my UI. The only divergence from the example is that I define **and** create my network as part of the ingress stack.
`ingress.yml`
```yml
version: "3.8"

networks:
  cluster-ingress:
    driver: overlay
    name: cluster-ingress

services:
  nginx:
    image: garutilorenzo/docker-swarm-ingress:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - cluster-ingress
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role==manager"
```
`ui.yml`
```yml
version: "3.8"

networks:
  cluster-ingress:
    driver: overlay
    external: true
    name: cluster-ingress

services:
  server:
    image: 976750617193.dkr.ecr.ap-south-1.amazonaws.com/wecoach-ui-registry:0.7.1
    command: "npm run dev -- --hostname 0.0.0.0 --port 3000"
    networks:
      - cluster-ingress
    deploy:
      replicas: 1
      labels:
        ingress.host: revamp.wecoach.ai
        ingress.port: 3000
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==worker"
          - "node.labels.is_ui_node==true"
```
I also verified in the manager node and the corresponding worker node that the network is present
`manager`
```bash
[
    {
        "Name":"cluster-ingress",
        "Id":"0lw683oo2hemy4bx4xe66b7yw",
        "Created":"2024-01-24T06:22:13.646361363Z",
        "Scope":"swarm",
        "Driver":"overlay",
        "EnableIPv6":false,
        "IPAM":{
            "Driver":"default",
            "Options":null,
            "Config":[
                {
                    "Subnet":"10.0.1.0/24",
                    "Gateway":"10.0.1.1"
                }
            ]
        },
        "Internal":false,
        "Attachable":false,
        "Ingress":false,
        "ConfigFrom":{
            "Network":""
        },
        "ConfigOnly":false,
        "Containers":{
            "1cefcb60162713dd97671c7a1c90f32157504f9876bfaec1dba3b7453900e78d":{
                "Name":"visualizer_server.1.yju23e5kj8ldddmlgfd8kmsjg",
                "EndpointID":"9e430f9e13c7bc7d99c2f14fc45c6dc16b1092a1c9fdfe43cd540cecb185961a",
                "MacAddress":"02:42:0a:00:01:06",
                "IPv4Address":"10.0.1.6/24",
                "IPv6Address":""
            },
            "fb493c4b0b7f89e69f0a299f011a94b3377a948f373760446eda7df4fe89ce2d":{
                "Name":"ingress_nginx.1.8fqxmvy7laz0b8h8ou14on52g",
                "EndpointID":"d7bfd355f9e429b438b42cc0799577db67f6e584db00f46d996bf6eab40c7d8c",
                "MacAddress":"02:42:0a:00:01:03",
                "IPv4Address":"10.0.1.3/24",
                "IPv6Address":""
            },
            "lb-cluster-ingress":{
                "Name":"cluster-ingress-endpoint",
                "EndpointID":"1a157485a9c5501642b09c35c5be07c0d3e02d71698063d3f4c8a2735769292b",
                "MacAddress":"02:42:0a:00:01:04",
                "IPv4Address":"10.0.1.4/24",
                "IPv6Address":""
            }
        },
        "Options":{
            "com.docker.network.driver.overlay.vxlanid_list":"4097"
        },
        "Labels":{
            "com.docker.stack.namespace":"ingress"
        },
        "Peers":[
            {
                "Name":"c3dcd1846d95",
                "IP":"43.205.37.64"
            },
            {
                "Name":"5e221d22f134",
                "IP":"172.31.5.198"
            }
        ]
    }
]
```
`worker`
```bash
[
    {
        "Name":"cluster-ingress",
        "Id":"0lw683oo2hemy4bx4xe66b7yw",
        "Created":"2024-01-24T06:54:04.387191807Z",
        "Scope":"swarm",
        "Driver":"overlay",
        "EnableIPv6":false,
        "IPAM":{
            "Driver":"default",
            "Options":null,
            "Config":[
                {
                    "Subnet":"10.0.1.0/24",
                    "Gateway":"10.0.1.1"
                }
            ]
        },
        "Internal":false,
        "Attachable":false,
        "Ingress":false,
        "ConfigFrom":{
            "Network":""
        },
        "ConfigOnly":false,
        "Containers":{
            "1521a0e2236a441f06fdd3ffddab1e5e7cf3746c9962773e0d0cff057e808bf0":{
                "Name":"ui_server.1.nulos2x9sd9150ngno8j8xrrs",
                "EndpointID":"260ff82815aaf630deae7ae19b5f36e97f21a7a155db3b77aa90ae747f06ab1a",
                "MacAddress":"02:42:0a:00:01:0b",
                "IPv4Address":"10.0.1.11/24",
                "IPv6Address":""
            },
            "lb-cluster-ingress":{
                "Name":"cluster-ingress-endpoint",
                "EndpointID":"3226ddb945efc1e4c39adb1f578b6dd292a99293a307e4f8523f075d8bb62437",
                "MacAddress":"02:42:0a:00:01:09",
                "IPv4Address":"10.0.1.9/24",
                "IPv6Address":""
            }
        },
        "Options":{
            "com.docker.network.driver.overlay.vxlanid_list":"4097"
        },
        "Labels":{
            "com.docker.stack.namespace":"ingress"
        },
        "Peers":[
            {
                "Name":"c3dcd1846d95",
                "IP":"43.205.37.64"
            },
            {
                "Name":"5e221d22f134",
                "IP":"172.31.5.198"
            }
        ]
    }
]
```
