### ISSUE TITLE
Support for replicated services.

### ISSUE THREAD

**Issue by onlinejudge95** [garutilorenzo/docker-swarm-ingress#16]
I have a use case where I am running `prometheus's` `node_exporter` on all nodes of my cluster as part of the docker service. I want to have an ingress attached to each service container so that I can use that ingress name directly in my `prometheus.yml` file. One way would be to define the service 4 times and add a label corresponding to each service definition. I was wondering if there is a way I can do it using this ingress.
```yml
version: "3.8"

networks:
  cluster-ingress:
    driver: overlay
    external: true
    name: cluster-ingress
  node-exporter:
    driver: overlay
    attachable: true

services:
  node_exporter:
    image: prom/node-exporter:v1.7.0
    command: "--path.rootfs=/host"
    networks:
      - cluster-ingress
      - node-exporter
    volumes:
      - "/:/host:ro,rslave"
    deploy:
      mode: global
      placement:
        constraints:
          - "node.platform.os==linux"
```

**Comment by garutilorenzo** [comment]
Hi @onlinejudge95,

this will work out of the box with docker swarm. More info [here](https://docs.docker.com/engine/swarm/how-swarm-mode-works/services/)
When you connect to a service via docker swarm and if i service is replicated, swarm will route you requests to all the replicas.

**Example**

Replicated nginx:

```yaml
version: "3.8"
services:

  nginx:
    image: nginx:alpine
    networks:
      - ingress
    deploy:
      mode: global
      placement:
        constraints:
          - "node.platform.os==linux"
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        ingress.host: my-service.company.tld
```

Make some traffic:

```
curl -H "Host: my-service.company.tld" http://<SWARM_IP>
curl -H "Host: my-service.company.tld" http://<SWARM_IP>
curl -H "Host: my-service.company.tld" http://<SWARM_IP>
curl -H "Host: my-service.company.tld" http://<SWARM_IP>
....
...
...
```

Get the logs:

```
docker service logs -f replicated_service_nginx

replicated_service_nginx.0.prwqleqatysx@k8s-ubuntu-5    | 10.0.2.4 - - [23/Feb/2024:08:37:09 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/7.81.0" "10.0.0.2"
replicated_service_nginx.0.2pacme40xukj@k8s-ubuntu-3    | 10.0.2.4 - - [23/Feb/2024:08:37:13 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/7.81.0" "10.0.0.2"
replicated_service_nginx.0.t0nhox88rpiy@k8s-ubuntu-0    | 10.0.2.4 - - [23/Feb/2024:08:37:13 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/7.81.0" "10.0.0.2"
replicated_service_nginx.0.zitxadjtvfqr@k8s-ubuntu-2    | 10.0.2.4 - - [23/Feb/2024:08:37:13 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/7.81.0" "10.0.0.2"
replicated_service_nginx.0.5rb53jbaaiby@k8s-ubuntu-4    | 10.0.2.4 - - [23/Feb/2024:08:37:14 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/7.81.0" "10.0.0.2"
replicated_service_nginx.0.xp45af5259gj@k8s-ubuntu-1    | 10.0.2.4 - - [23/Feb/2024:08:37:14 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/7.81.0" "10.0.0.2"
replicated_service_nginx.0.prwqleqatysx@k8s-ubuntu-5    | 10.0.2.4 - - [23/Feb/2024:08:37:14 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/7.81.0" "10.0.0.2"
replicated_service_nginx.0.2pacme40xukj@k8s-ubuntu-3    | 10.0.2.4 - - [23/Feb/2024:08:37:14 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/7.81.0" "10.0.0.2"
replicated_service_nginx.0.t0nhox88rpiy@k8s-ubuntu-0    | 10.0.2.4 - - [23/Feb/2024:08:37:14 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/7.81.0" "10.0.0.2"
```

As you can see the requests are routed each time to a different *Pod*: prwqleqatysx, 0.2pacme40xukj, 0.t0nhox88rpiy etc
