### ISSUE TITLE
HA and Load balancer for docker Swarm

### ISSUE THREAD

**Issue by casualmatt** [garutilorenzo/docker-swarm-ingress#2]
Hello, 

1. Does the ingress script work as a load balancer in docker Swarm? If yes, does it requires additional settings?
2. If the volume with the SSL cert is shared between 2 nginx ingress services, do they work properly in HA?

**Comment by garutilorenzo** [comment]
Hi @casualmatt 

yes the ingress controller act also as load balancer. You don't need any other configuration. [Ref.](https://docs.docker.com/engine/swarm/ingress/#publish-a-port-for-a-service).
There is no volume in this setup, only secrets are used. Secrets are shared between all the nodes of the cluster an they will be always available to all nodes.

**Comment by casualmatt** [comment]
Ciao Lorenzo, 
should I expose with "published" a specific port for the services? I would prefer to not do that to force every incoming request to go through the nginx proxy. 

```docker-compose.yaml
version: '3'
services:
  app:
    image: 'mybackend'
    restart: unless-stopped
    ports:
      - '3000:3000'
    labels:
      - ingress.host: mydomain.ch
    deploy:
      replicas: 2
```

Those that work with load balancing correctly?

**Comment by garutilorenzo** [comment]
To do this remove the exposed port (3000). You can reach the service with mydomain.ch

```yaml
version: '3'
services:
  app:
    image: 'mybackend'
    restart: unless-stopped
    labels:
      - ingress.host: mydomain.ch
      - ingress.port: 3000
    deploy:
      replicas: 2
```
